apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline

  workspaces:
    - name: shared-workspace
      emptyDir: {}

  params: []
